apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: debating-backend-pod-chaos
  namespace: {{ .Release.Namespace }}
spec:
  action: pod-kill
  mode: one
  scheduler:
    cron: "@every 1m"
  selector:
    namespaces:
      - {{ .Release.Namespace }}
    labelSelectors:
      'app': 'backend'